from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from webworkflows.synthesis import (
    AgentJsonSynthesisBackend,
    CodexAppServerSynthesisBackend,
    FakeSynthesisBackend,
    SynthesisBackend,
)


def create_synthesis_backend(
    name: str,
    *,
    workflow_json_file: str | Path | None = None,
    base_workflow_json: dict[str, Any] | None = None,
    cwd: str | Path | None = None,
) -> SynthesisBackend:
    if name == "codex":
        return CodexAppServerSynthesisBackend(cwd=cwd)
    if name == "agent-json":
        if not workflow_json_file:
            raise ValueError("--workflow-json-file is required with --synthesizer agent-json")
        return AgentJsonSynthesisBackend(workflow_json_path=workflow_json_file)
    if name == "fake-copy":
        if base_workflow_json is None:
            raise ValueError("base_workflow_json is required with fake-copy")
        copied = json.loads(json.dumps(base_workflow_json, ensure_ascii=False))
        copied["body_md"] = copied["body_md"] + "\n\nDraft update generated by fake-copy."
        return FakeSynthesisBackend(response=copied)
    raise ValueError(f"unknown update synthesizer: {name}")
