/**
 * CSS Selector generator for recording user interactions.
 * Generates unique, resilient selectors following a priority chain.
 */

const AUTO_ID_PATTERNS = [
  /^:r[0-9a-z]+:$/,    // React auto-generated
  /^react-/,
  /^ember\d+/,
  /^[a-f0-9]{8,}$/,    // hash-like
  /^\d+$/,             // numeric only
  /^js-/,
  /^_/,
];

const IGNORED_CLASS_PATTERNS = [
  /^css-/,       // CSS-in-JS
  /^sc-/,        // styled-components
  /^emotion-/,
  /^_[a-zA-Z0-9]{5,}/, // CSS modules hashes
  /^[a-z]{1,3}-\[/, // Tailwind arbitrary values
];

const TEST_ATTRIBUTES = ['data-testid', 'data-qa', 'data-cy', 'data-test'];

function escapeSelector(value: string): string {
  if (typeof CSS !== 'undefined' && CSS.escape) {
    return CSS.escape(value);
  }
  return value.replace(/([^\w-])/g, '\\$1');
}

function isUniqueSelector(selector: string): boolean {
  try {
    return document.querySelectorAll(selector).length === 1;
  } catch {
    return false;
  }
}

function isAutoGeneratedId(id: string): boolean {
  return AUTO_ID_PATTERNS.some((pattern) => pattern.test(id));
}

function isUsefulClass(cls: string): boolean {
  return !IGNORED_CLASS_PATTERNS.some((pattern) => pattern.test(cls));
}

function tryIdSelector(el: Element): string | null {
  if (el.id && !isAutoGeneratedId(el.id)) {
    const selector = `#${escapeSelector(el.id)}`;
    if (isUniqueSelector(selector)) return selector;
  }
  return null;
}

function tryTestAttributes(el: Element): string | null {
  for (const attr of TEST_ATTRIBUTES) {
    const value = el.getAttribute(attr);
    if (value) {
      const selector = `[${attr}="${escapeSelector(value)}"]`;
      if (isUniqueSelector(selector)) return selector;
    }
  }
  return null;
}

function tryNameAttribute(el: Element): string | null {
  const name = el.getAttribute('name');
  if (name) {
    const tag = el.tagName.toLowerCase();
    const selector = `${tag}[name="${escapeSelector(name)}"]`;
    if (isUniqueSelector(selector)) return selector;
  }
  return null;
}

function tryAriaAttributes(el: Element): string | null {
  const role = el.getAttribute('role');
  const label = el.getAttribute('aria-label');

  if (role && label) {
    const selector = `[role="${escapeSelector(role)}"][aria-label="${escapeSelector(label)}"]`;
    if (isUniqueSelector(selector)) return selector;
  }
  if (label) {
    const selector = `[aria-label="${escapeSelector(label)}"]`;
    if (isUniqueSelector(selector)) return selector;
  }
  if (role) {
    const tag = el.tagName.toLowerCase();
    const selector = `${tag}[role="${escapeSelector(role)}"]`;
    if (isUniqueSelector(selector)) return selector;
  }
  return null;
}

function tryClassCombination(el: Element): string | null {
  const classes = Array.from(el.classList).filter(isUsefulClass);
  if (classes.length === 0) return null;

  const tag = el.tagName.toLowerCase();

  // Try single class
  for (const cls of classes) {
    const selector = `${tag}.${escapeSelector(cls)}`;
    if (isUniqueSelector(selector)) return selector;
  }

  // Try class combinations (up to 3)
  for (let i = 0; i < classes.length; i++) {
    for (let j = i + 1; j < classes.length && j < i + 3; j++) {
      const selector = `${tag}.${escapeSelector(classes[i])}.${escapeSelector(classes[j])}`;
      if (isUniqueSelector(selector)) return selector;
    }
  }

  return null;
}

function tryAttributeCombination(el: Element): string | null {
  const tag = el.tagName.toLowerCase();
  const attrs: string[] = [];

  const type = el.getAttribute('type');
  if (type) attrs.push(`[type="${escapeSelector(type)}"]`);

  const placeholder = el.getAttribute('placeholder');
  if (placeholder) attrs.push(`[placeholder="${escapeSelector(placeholder)}"]`);

  const href = el.getAttribute('href');
  if (href && href !== '#' && href !== '') attrs.push(`[href="${escapeSelector(href)}"]`);

  const title = el.getAttribute('title');
  if (title) attrs.push(`[title="${escapeSelector(title)}"]`);

  // Try with text content for buttons/links
  if (['button', 'a'].includes(tag)) {
    const text = el.textContent?.trim();
    if (text && text.length < 50) {
      // combine tag + type if available
      for (const attr of attrs) {
        const selector = `${tag}${attr}`;
        if (isUniqueSelector(selector)) return selector;
      }
    }
  }

  for (const attr of attrs) {
    const selector = `${tag}${attr}`;
    if (isUniqueSelector(selector)) return selector;
  }

  // Try combining two attributes
  for (let i = 0; i < attrs.length; i++) {
    for (let j = i + 1; j < attrs.length; j++) {
      const selector = `${tag}${attrs[i]}${attrs[j]}`;
      if (isUniqueSelector(selector)) return selector;
    }
  }

  return null;
}

function tryParentContext(el: Element): string | null {
  const parent = el.parentElement;
  if (!parent || parent === document.body) return null;

  const parentSelector =
    tryIdSelector(parent) ??
    tryTestAttributes(parent) ??
    tryClassCombination(parent);

  if (!parentSelector) return null;

  const tag = el.tagName.toLowerCase();

  // Try tag only under parent
  let selector = `${parentSelector} > ${tag}`;
  if (isUniqueSelector(selector)) return selector;

  // Try with class
  const classes = Array.from(el.classList).filter(isUsefulClass);
  for (const cls of classes) {
    selector = `${parentSelector} > ${tag}.${escapeSelector(cls)}`;
    if (isUniqueSelector(selector)) return selector;
  }

  return null;
}

function nthChildPath(el: Element): string {
  const parts: string[] = [];
  let current: Element | null = el;

  while (current && current !== document.body && current !== document.documentElement) {
    const parent: Element | null = current.parentElement;
    if (!parent) break;

    const siblings = Array.from(parent.children);
    const index = siblings.indexOf(current) + 1;
    const tag = current.tagName.toLowerCase();
    parts.unshift(`${tag}:nth-child(${index})`);

    // Check if we have enough context
    const selector = parts.join(' > ');
    if (isUniqueSelector(selector)) return selector;

    current = parent;
  }

  return parts.join(' > ');
}

export function generateSelector(el: Element): string {
  return (
    tryIdSelector(el) ??
    tryTestAttributes(el) ??
    tryNameAttribute(el) ??
    tryAriaAttributes(el) ??
    tryClassCombination(el) ??
    tryAttributeCombination(el) ??
    tryParentContext(el) ??
    nthChildPath(el)
  );
}

export function generateLabel(el: Element, action: string): string {
  const tag = el.tagName.toLowerCase();

  if (action === 'input') {
    const name = el.getAttribute('name') || el.getAttribute('placeholder') || el.getAttribute('aria-label') || '';
    if (name) return `Fill ${name}`;
    return `Fill ${tag}`;
  }

  if (action === 'keydown') {
    return `Press key`;
  }

  // Click actions
  const text = el.textContent?.trim();
  if (text && text.length < 30) return `Click ${text}`;

  const ariaLabel = el.getAttribute('aria-label');
  if (ariaLabel) return `Click ${ariaLabel}`;

  const title = el.getAttribute('title');
  if (title) return `Click ${title}`;

  if (tag === 'a') return 'Click link';
  if (tag === 'button') return 'Click button';
  if (tag === 'input') {
    const type = el.getAttribute('type');
    return `Click ${type || 'input'}`;
  }

  return `Click ${tag}`;
}
